name: Run Python Tests
on: push

jobs:
  ubuntu_39:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare config folder
        run: mv config_sample config

      - name: Run tests
        run: python test.py

  ubuntu_310:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare config folder
        run: mv config_sample config

      - name: Run tests
        run: python test.py

  ubuntu_311:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare config folder
        run: mv config_sample config

      - name: Run tests
        run: python test.py
